version: '3.3'
services:
  app:
    container_name: api
    build: .
    env_file:
      - ./.env
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_HOST: localhost
    volumes:
      - .:/app/
    entrypoint: ['/bin/bash', './entrypoint.sh']
    depends_on:
      - db

  db:
    container_name: ${DB_NAME_DEV}
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${DB_USER_DEV}
      - POSTGRES_PASSWORD=${DB_PWD_DEV}

volumes:
  app-db-data:
