version: '3.7'
services:
  db:
    container_name: ${POSTGRES_SERVER_DEV}
    image: postgres
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${DB_USER_DEV}
      - POSTGRES_PASSWORD=${DB_PWD_DEV}
      - POSTGRES_DB=${DB_NAME_DEV}

  app:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app/
    depends_on:
      - db
    entrypoint: ['/bin/bash', './entrypoint.sh']

volumes:
  app-db-data: