version: "3"
services:
  app:
    container_name: api
    build: .
    command: npm run dev
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: host.docker.internal
    volumes:
      - .:/app/
    depends_on:
      - db

  db:
    container_name: ${DB_NAME_DEV}
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${DB_USER_DEV}
      - POSTGRES_PASSWORD=${DB_PWD_DEV}
    restart: always

  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - db
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   restart: unless-stopped

volumes:
  app-db-data: